name: test
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts --no-audit
  lint-js:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --no-audit
      - run: npm run lint:js
  lint-webext:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: freaktechnik/web-ext-lint@v1
